apiVersion: v1 # Versão da API utilizada para o recurso
kind: Secret # Tipo de recurso (Pod no caso)
metadata:
  name: servidor-python-secrets # Nome do segredo que será referenciado em outros recursos
type: Opaque # Tipo de segredo Opaque, que significa que contém dados não estruturados
data:
  USERNAME: "a3ViZXJuZXRlcw==" # Dados codificados em base64 para o nome de usuário (Ex: kubernetes)
  PASSWORD: "c291LXVtLXNlZ3JlZG8=" # Dados codificados em base64 para a senha (Ex: sou-um-segredo)
